Create MANIFEST.in
otherwise some files would be missing in Pypi's SDIST archives:

```
Local copy of remote index is up-to-date and will be used.

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    ~] dev-python/whirlpool-sixth-sense-0.15.1::HomeAssistantRepository  USE="test" PYTHON_TARGETS="python3_9 -python3_8 -python3_10" 0 KiB
[ebuild  N    ~]  dev-python/aioconsole-0.3.2::HomeAssistantRepository  USE="test" PYTHON_TARGETS="python3_9 -python3_8 -python3_10" 0 KiB

Total: 2 packages (2 new), Size of downloads: 0 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 2) dev-python/aioconsole-0.3.2::HomeAssistantRepository
>>> Installing (1 of 2) dev-python/aioconsole-0.3.2::HomeAssistantRepository
>>> Emerging (2 of 2) dev-python/whirlpool-sixth-sense-0.15.1::HomeAssistantRepository
>>> Failed to emerge dev-python/whirlpool-sixth-sense-0.15.1, Log file:
>>>  '/var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/temp/build.log'
>>> Jobs: 1 of 2 complete, 1 failed                 Load avg: 0.46, 0.19, 0.11
 * Package:    dev-python/whirlpool-sixth-sense-0.15.1
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   amfcalt@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_9 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking whirlpool-sixth-sense-0.15.1.tar.gz to /var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work
>>> Source unpacked in /var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work
>>> Preparing source in /var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work/whirlpool_sixth_sense-0.15.1 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work/whirlpool_sixth_sense-0.15.1 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work/whirlpool_sixth_sense-0.15.1 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 6
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/whirlpool-sixth-sense-0.15.1/work/whirlpool_sixth_sense-0.15.1/setup.py", line 6, in <module>
    with open("requirements.txt") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/whirlpool-sixth-sense-0.15.1::HomeAssistantRepository failed (compile phase):
 *   (no error message)
 *
```